[tool.poetry]
name = "division-territorial"
version = "0.1.0"
description = ""
authors = ["Jorge Massih <jorgmassih@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyterlab = "^4.2.3"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
sqlalchemy = "^2.0.31"
pymysql = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
